language: node_js

env:
  - TARGET=test

node_js:
  - 10
  - 12
  - 14
  - node

matrix:
  include:
    - name: Lint
      node_js: 14
      env:
        - TARGET=lint
    - name: Coverage
      node_js: 14
      env:
        - TARGET=coverage
    - name: Documentation
      node_js: 14
      env:
        - TARGET=test-docs
    - name: Chrome headless
      node_js: 14
      env:
        - TARGET=test-headless

addons:
  chrome: stable

script: npm run $TARGET

after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
